# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Feb 14 18:14:09 2009

import wx
import wx.lib.masked

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

## SOCKET CONSTANTS ##
NOT_CONNECTED = 0
CONNECTED = 2
CONNECTING = 1
ERROR = -1

class ConnectDialog(wx.Dialog):
    def __init__(self, parent, id, socketCondition):
        # begin wxGlade: ConnectDialog.__init__
        #kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.STAY_ON_TOP
        wx.Dialog.__init__(self, parent, id, style = wx.DEFAULT_DIALOG_STYLE)
        self.sizer_2_staticbox = wx.StaticBox(self, -1, "Insert Robot's IP")
        
        #self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.text_ctrl_1 = wx.lib.masked.IpAddrCtrl(self, -1, '', (0,30))
        self.text_ctrl_1.SetValue('192.168.0.99')  
        self.Abort_button = wx.Button(self, wx.ID_CANCEL, "")
        self.OK_button = wx.Button(self, wx.ID_OK, "")
        self.socketCondition = socketCondition
        self.connectionStatus = NOT_CONNECTED

        self.parent = parent
        self.OK_button.Bind(wx.EVT_BUTTON,self.__onOK)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ConnectDialog.__set_properties
        self.SetTitle("Connect")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("icons/connect.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((249, 115))
        #self.text_ctrl_1.SetMinSize((200, 35))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConnectDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
        sizer_2.Add(self.text_ctrl_1, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_2, 1, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.Abort_button, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.OK_button, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def GetIP(self):
        return self.text_ctrl_1.GetAddress()

    def SetConnectionStatus(self,status):
        self.connectionStatus = status

    def GetConnectionStatus(self):
        #print self.connectionStatus
        return self.connectionStatus
    
    def __onOK(self,evt):
        self.socketCondition.acquire()
        self.socketCondition.notify()
        self.socketCondition.release()

        self.connectingDialog = wx.ProgressDialog('Connecting...','Please wait, trying to connect...',style = wx.STAY_ON_TOP | wx.DEFAULT_DIALOG_STYLE |wx.PD_CAN_ABORT)
        
        self.connectingDialog.Show()
        while True:
            self.socketCondition.acquire()
            self.socketCondition.wait(0.1)
            
            status = self.GetConnectionStatus()
            if status == CONNECTING:
                self.connectingDialog.Pulse()
                #print "mi sto connettendo..."
            if status == CONNECTED:
                self.connectingDialog.Update(100,"Connected!")
                self.connectingDialog.Update(100)
                self.Destroy()
                break
            if status == ERROR:
                self.connectingDialog.Update(100,"Error: unable to connect!")
                break
            
        #self.connectingDialog = Connecting(self,-1,self.socketCondition)
        #print "cia"
        #self.connectingDialog.ShowModal()
    

# end of class ConnectDialog


