# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Feb 17 13:06:43 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import customWidgets
# end wxGlade

class RobotStatus(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RobotStatus.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizer_15_staticbox = wx.StaticBox(self, -1, "sx speed")
        self.sizer_14_staticbox = wx.StaticBox(self, -1, "obstacle sensor")
        self.sizer_16_staticbox = wx.StaticBox(self, -1, "dx speed")
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Logic")
        self.sizer_6_staticbox = wx.StaticBox(self, -1, "Motor")
        self.sizer_7_staticbox = wx.StaticBox(self, -1, "Servo")
        self.sizer_13_staticbox = wx.StaticBox(self, -1, "obstacle sensor")
        self.panel_1 = wx.Panel(self, -1)
        self.panel_11 = wx.Panel(self, -1)
        self.panel_9 = wx.Panel(self, -1)
        self.panel_8 = wx.Panel(self, -1)
        self.bitmap_2 = wx.StaticBitmap(self, -1, wx.Bitmap("images/robot.png", wx.BITMAP_TYPE_ANY))
        self.panel_10 = wx.Panel(self, -1)
        self.text_ctrl_4 = wx.TextCtrl(self, -1, "")
        self.panel_12 = wx.Panel(self, -1)
        self.text_ctrl_5 = wx.TextCtrl(self, -1, "")
        self.window_2 = customWidgets.Battery(self, -1,(65,110))
        self.window_3 = customWidgets.Battery(self, -1,(135,110))
        self.window_4 = customWidgets.Battery(self, -1,(65,110))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RobotStatus.__set_properties
        self.SetTitle("RobotStatus")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("icons/Robot.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((312, 393))
        self.panel_11.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.text_ctrl_4.SetMinSize((65, 27))
        self.panel_12.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.text_ctrl_5.SetMinSize((65, 27))
        self.window_2.SetMinSize((65, 110))
        self.window_3.SetMinSize((135, 110))
        self.window_4.SetMinSize((65, 110))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RobotStatus.__do_layout
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_3 = wx.FlexGridSizer(3, 3, 0, 0)
        sizer_7 = wx.StaticBoxSizer(self.sizer_7_staticbox, wx.HORIZONTAL)
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
        sizer_16 = wx.StaticBoxSizer(self.sizer_16_staticbox, wx.HORIZONTAL)
        sizer_14 = wx.StaticBoxSizer(self.sizer_14_staticbox, wx.HORIZONTAL)
        sizer_15 = wx.StaticBoxSizer(self.sizer_15_staticbox, wx.HORIZONTAL)
        sizer_13 = wx.StaticBoxSizer(self.sizer_13_staticbox, wx.HORIZONTAL)
        grid_sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_13.Add(self.panel_11, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_13, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_9, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_8, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.bitmap_2, 0, 0, 0)
        grid_sizer_3.Add(self.panel_10, 1, wx.EXPAND, 0)
        sizer_15.Add(self.text_ctrl_4, 0, 0, 0)
        grid_sizer_3.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_14.Add(self.panel_12, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_16.Add(self.text_ctrl_5, 0, 0, 0)
        grid_sizer_3.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_3.Add(self.window_2, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_6.Add(self.window_3, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.window_4, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_12.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_12)
        self.Layout()
        self.SetMinSize((300, 385))
        # end wxGlade

# end of class RobotStatus


